// src/components/portfolio/portfolio-drawer.jsx
import { useState } from "react";
import { Briefcase } from "tabler-icons-react";
import useScrollPosition from "../../utils/custom-hooks";
// components
import ProjectList from "./project-list";
import Drawer from "../ui/Drawer";
import IconButton from "../ui/IconButton";

function PortfolioDrawer() {
  const [opened, setOpened] = useState(false);
  const scrollPosition = useScrollPosition();

  const handleOnClose = () => {
    setOpened(false);
    setTimeout(() => window.scrollTo(0, scrollPosition), 21);
  };

  return (
    <>
      <Drawer
        className="font-montserrat"
        open={opened}
        onClose={handleOnClose}
        title="PROJECTS"
        size="lg"
        lockScroll={false}
      >
        <ProjectList />
      </Drawer>

      <div className="flex justify-center">
        <IconButton size={40} ariaLabel="Open projects" onClick={() => setOpened(true)}>
          <Briefcase style={{ color: "#a0522d" }} size={40} />
        </IconButton>
      </div>
    </>
  );
}

export default PortfolioDrawer;

// src/components/portfolio/PortfolioDrawer.vue
<script setup>
import { ref } from "vue";
import { IconBriefcase } from "@tabler/icons-vue";
import { useScrollPosition } from "../../utils/useScrollPosition";
import Drawer from "../ui/Drawer.vue";
import IconButton from "../ui/IconButton.vue";
import ProjectList from "./ProjectList.vue";

const opened = ref(false);
const scrollPosition = useScrollPosition();

const handleOnClose = () => {
  opened.value = false;
  setTimeout(() => window.scrollTo(0, scrollPosition.value), 21);
};
</script>

<template>
  <Drawer
    panelClass="font-montserrat"
    :open="opened"
    title="PROJECTS"
    size="lg"
    :lockScroll="false"
    @close="handleOnClose"
  >
    <ProjectList />
  </Drawer>

  <div class="flex justify-center">
    <IconButton :size="40" ariaLabel="Open projects" @click="opened = true">
      <IconBriefcase :size="40" color="#a0522d" />
    </IconButton>
  </div>
</template>
