// src/components/portfolio/projects-page.jsx
import { PROJECTS } from "../../data/projects-info";
// components
import ProjectCard from "./project-card";

function ProjectsPage() {
  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 mb-8">
      {PROJECTS.map((project, index) => (
        <ProjectCard
          key={index}
          projectTitle={project.title}
          projectDescription={project.description}
          projectTechnologies={project.technologies}
          projectImage={project.image}
          projectId={`${index}`}
          projectLink={project.link}
        />
      ))}
    </div>
  );
}

export default ProjectsPage;

// src/components/portfolio/ProjectsPage.vue
<script setup>
import { PROJECTS } from "../../data/projects-info";
import ProjectCard from "./ProjectCard.vue";
</script>

<template>
  <div class="grid grid-cols-1 sm:grid-cols-2 gap-6 mb-8">
    <ProjectCard
      v-for="(project, index) in PROJECTS"
      :key="index"
      :projectTitle="project.title"
      :projectDescription="project.description"
      :projectTechnologies="project.technologies"
      :projectImage="project.image"
      :projectId="String(index)"
      :projectLink="project.link"
    />
  </div>
</template>
