// src/components/contact/contact-gmail-modal.jsx
import { useState } from "react";
import { BrandGmail } from "tabler-icons-react";
// components
import ContactForm from "./contact-form";
import Modal from "../ui/Modal";
import IconButton from "../ui/IconButton";

function GmailModal() {
  const [opened, setOpened] = useState(false);

  return (
    <>
      <Modal
        open={opened}
        onClose={() => setOpened(false)}
        title="Let's talk"
      >
        <ContactForm />
      </Modal>

      <div className="flex justify-center">
        <IconButton size={40} ariaLabel="Open email" onClick={() => setOpened(true)}>
          <BrandGmail style={{ color: "#e03c31" }} size={40} />
        </IconButton>
      </div>
    </>
  );
}

export default GmailModal;

// src/components/contact/ContactGmailModal.vue
<script setup>
import { ref } from "vue";
import { IconBrandGmail } from "@tabler/icons-vue";
import Modal from "../ui/Modal.vue";
import IconButton from "../ui/IconButton.vue";
import ContactForm from "./ContactForm.vue";

const opened = ref(false);
</script>

<template>
  <Modal :open="opened" title="Let's talk" @close="opened = false">
    <ContactForm />
  </Modal>

  <div class="flex justify-center">
    <IconButton :size="40" ariaLabel="Open email" @click="opened = true">
      <IconBrandGmail :size="40" color="#e03c31" />
    </IconButton>
  </div>
</template>
