// src/components/nav-bar.jsx
import { Home } from "tabler-icons-react";
// components
import PortfolioDrawer from "./portfolio/portfolio-drawer";
import ContactDrawer from "./contact/contact-drawer";
import IconButton from "./ui/IconButton";

function Navbar({ setBounce, darkTheme }) {
  const homeOnClick = () => {
    window.scrollTo(0, 0);
    setBounce(true);
    setTimeout(() => {
      setBounce(false);
    }, 1000);
  }
  return (
    <div className="nav_bar border-2 flex justify-evenly py-4 sticky top-0 z-10 bg-white"
    style={{ background: darkTheme ? '#1A1B1E' : 'white' }}>
      <PortfolioDrawer />
      <IconButton size={40} ariaLabel="Home" onClick={homeOnClick}>
        <Home style={{color: "#228b22"}} size={40} />
      </IconButton>
      <ContactDrawer />
    </div>
  );
}

export default Navbar;

// src/components/NavBar.vue
<script setup>
import { IconHome } from "@tabler/icons-vue";
import IconButton from "./ui/IconButton.vue";
import PortfolioDrawer from "./portfolio/PortfolioDrawer.vue";
import ContactDrawer from "./contact/ContactDrawer.vue";

const props = defineProps({
  darkTheme: { type: Boolean, default: false },
});

const emit = defineEmits(["bounce"]);

const homeOnClick = () => {
  window.scrollTo(0, 0);
  emit("bounce");
};
</script>

<template>
  <div
    class="nav_bar border-2 flex justify-evenly py-4 sticky top-0 z-10"
    :style="{ background: props.darkTheme ? '#1A1B1E' : 'white' }"
  >
    <PortfolioDrawer />

    <IconButton :size="40" ariaLabel="Home" @click="homeOnClick">
      <IconHome :size="40" color="#228b22" />
    </IconButton>

    <ContactDrawer />
  </div>
</template>
